### PR TITLE
feat: Multicall v3

### PR DESCRIPTION
**Pull request by BobTheBuidler**

### CODE REVIEW

**Comment by 007vasy** [comment]
@BobTheBuidler ready for review, works, tested on 10+ chains

**Comment by 007vasy** [comment]
@banteg, a bit later, but as promised

closes: https://github.com/banteg/multicall.py/issues/49

**Comment by 007vasy** [comment]
@BobTheBuidler I cannot convert this to ready for review

**Review by banteg — APPROVED** [review]

**Comment by banteg** [comment]
thank you for your contribution @007vasy, released this as 0.7.0

**Pull request merged**
