### PR TITLE
add OEC network

### PR DESCRIPTION
**Pull request by heki-ru**
support for OEC mainnet (formerly known as OKEx)

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
Hey @heki-ru , do you happen to have a link to the source code for this in an Okc block explorer? A quick Google led me to Oklink but the contract appears non-verified on there.

**Comment by heki-ru** [comment]
Unfortunately I don't. Oklink is the only explorer for OEC and it have troubles with verifying contracts. I can only confirm it's working, because I currently use it by myself.

**Comment by DefiDebauchery** [comment]
This may be worthy of getting the [Multicallv3](https://github.com/mds1/multicall) maintainer involved. For gas costs, he'll deploy the contract at a static address on any EVM chain. If nothing else, it would lend itself to being more trusted if it remained unverified due to explorer issues.

**Comment by heki-ru** [comment]
#https://github.com/mds1/multicall/issues/21

**Pull request closed without merging**
